image: Visual Studio 2019

environment:
  matrix:
    - JAVA_VERSION: "8"
    - JAVA_VERSION: "11"

install:
  - ps: |
      choco install jdk%JAVA_VERSION% -y
      refreshenv
  - cmd: java -version

build_script:
  - ps: |
      if (Test-Path compile-jar.bat) {
        compile-jar.bat
      } else {
        Write-Host 'compile-jar.bat not found, attempting shell script...'
      }
  - bash: |
      if [ -f compile-jar.sh ]; then
        bash compile-jar.sh
      else
        echo "compile-jar.sh not found"
      fi

artifacts:
  - path: TGT.jar
    name: TGT-%APPVEYOR_REPO_BRANCH%-%JAVA_VERSION%
    type: zip
