name: Build TGT JAR

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Make the compile script executable
      run: chmod +x compile-jar.sh

    - name: Build the JAR
      run: ./compile-jar.sh

    - name: Upload JAR artifact
      uses: actions/upload-artifact@v2
      with:
        name: TGT
        path: |
          *.jar
          src/*.jar
